[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "file-query-mcp"
version = "0.1.0"
dependencies = [
    "mcp[cli]",
    "httpx",
    "duckdb",
    "polars",
    "pandas",
    "pyarrow>=21.0.0",
    "pydantic>=2.11.7",
]
